//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the end of this questionnaire. Press the &quot;Send&quot; button to complete the evaluation..
        /// </summary>
        internal static string AcdcCompletedText {
            get {
                return ResourceManager.GetString("AcdcCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification code you entered appears to be invalid. Please try again..
        /// </summary>
        internal static string AuthenticationFailedText {
            get {
                return ResourceManager.GetString("AuthenticationFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the end of this questionnaire. Press the &quot;Send&quot; button to complete the evaluation..
        /// </summary>
        internal static string CoachingCompletedText {
            get {
                return ResourceManager.GetString("CoachingCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation completed.
        /// </summary>
        internal static string CompletedTitle {
            get {
                return ResourceManager.GetString("CompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactperson was not present.
        /// </summary>
        internal static string ContactpersonNotPresent {
            get {
                return ResourceManager.GetString("ContactpersonNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactperson was present.
        /// </summary>
        internal static string ContactpersonPresent {
            get {
                return ResourceManager.GetString("ContactpersonPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the end of this questionnaire. Press the &quot;Send&quot; button to complete the evaluation..
        /// </summary>
        internal static string CustomProjectsCompletedText {
            get {
                return ResourceManager.GetString("CustomProjectsCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dissatisfied.
        /// </summary>
        internal static string Dissatisfied {
            get {
                return ResourceManager.GetString("Dissatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We encountered a problem while processing the evaluation form. Click the &quot;Back&quot; button to try and go back to previous page or close the browser and try to open the evaluation form again. We apologize for the inconvenience..
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Quintessence Consulting we constantly work to improve the quality of our service. With that in mind we would like to ask you a number of questions about the quality of the assessment and development activities you recently took part in at Quintessence..
        /// </summary>
        internal static string EvaluationFormAcdcIntroText {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you satisfied with how long it takes to plan and set up an assessment centre?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion01 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you satisfied with the information the participants received to prepare?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion02 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you satisfied with how long it takes to generate a report?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion03 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you satisfied with the way in which your competence profile was established?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion04 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Were the competences relevant to the job assessed?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion05 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you satisfied with the service of the client assistants?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion06 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you satisfied with the process of invoicing?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion07 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How important is it for you that the same assessors assess all participants with regard to the same job?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion08 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your general impression of the quality of the reports?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion09 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tell us your thoughts on the following aspects of the reports.
        ///&lt;ul&gt;
        ///&lt;li&gt;Are they clear?&lt;/li&gt;
        ///&lt;li&gt;Are they to the point?&lt;/li&gt;
        ///&lt;li&gt;Is the score in line with the observations?&lt;/li&gt;
        ///&lt;li&gt;Is the style sufficiently appreciative?&lt;/li&gt;
        ///&lt;li&gt;Do participants recognise themselves in the observations?&lt;/li&gt;
        ///&lt;li&gt;Do line managers recognise the participants in the observations?&lt;/li&gt;
        ///&lt;li&gt;Are they grammatically correct?&lt;/li&gt;
        ///&lt;li&gt;Are they easy to follow?&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion10 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do the reports give you a good idea of the performance you can expect from the participant?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion11 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are adequate points made to back up the recommendation?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion12 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the summary at the beginning a source of added value for you?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion13 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the description of the results of the personality questionnaire clear enough?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion14 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you satisfied with the paragraph about cultural fit?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion15 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there sufficient uniformity across the reports of the various assessors?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion16 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did the assessor call you the day after the assessment/development centre to give feedback on the assessment/development centre?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion17 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this call a source of added value for you? What aspects of the phone feedback do you appreciate?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion18 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you tend to follow the recommendation you are given?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion19 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion19_19A {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion19_19A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why not?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion19_19B {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion19_19B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What aspects play a role in the recruitment/selection decision for a given candidate?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion20 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What feedback do you get from participants after the assessment or development centre?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion21 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do participants respond after they have received the feedback (by phone or face-to-face)?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion22 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do participants respond to the following?
        ///            &lt;ul&gt;
        ///                &lt;li&gt;Negative recommendations&lt;/li&gt;
        ///                &lt;li&gt;Positive recommendations&lt;/li&gt;
        ///            &lt;/ul&gt;.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion23 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you feel we could improve our service?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion24 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have specific recommendations to improve our assessment and development offerings?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion25 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are there any other comments you would like to make?.
        /// </summary>
        internal static string EvaluationFormAcdcQuestion26 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcQuestion26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation/Follow-up.
        /// </summary>
        internal static string EvaluationFormAcdcTitleBlock1 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcTitleBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written report.
        /// </summary>
        internal static string EvaluationFormAcdcTitleBlock2 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcTitleBlock2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone feedback to client.
        /// </summary>
        internal static string EvaluationFormAcdcTitleBlock3 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcTitleBlock3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What happens next.
        /// </summary>
        internal static string EvaluationFormAcdcTitleBlock4 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcTitleBlock4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback to participants.
        /// </summary>
        internal static string EvaluationFormAcdcTitleBlock5 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcTitleBlock5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions/Recommendations.
        /// </summary>
        internal static string EvaluationFormAcdcTitleBlock6 {
            get {
                return ResourceManager.GetString("EvaluationFormAcdcTitleBlock6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Quintessence Consulting we constantly work to improve the quality of our service. In doing so, your opinion is very important. With that in mind, we would like to ask you a number of questions about the quality of the coaching activities you recently took part in with Quintessence coaches..
        /// </summary>
        internal static string EvaluationFormCoachingIntroText {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To what degree did you receive sufficient prior information about what coaching is and what you could expect from this coaching path? (quotation, phone call, personal contact)?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion01 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What information would you have found useful to have in advance?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion02 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was there an intake interview at which other people than simply the coach and the coachee were present?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion03 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who was present at this intake interview?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion04A {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion04A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To what degree was attending this intake interview a source of added value for you?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion04A_41A_411 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion04A_41A_411", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To what degree were clear arrangements made with regard to next steps in the coaching path?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion04A_41A_412 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion04A_41A_412", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to make any other comments about the intake interview?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion04A_41A_413 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion04A_41A_413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What comments have been made to you about the intake interview?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion04A_41B_411 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion04A_41B_411", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to be present in the future?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion04A_41B_412 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion04A_41B_412", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like other people to be present in the future?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion04B {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion04B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was there a feedback interview?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion05 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who was present at this feedback interview?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion05_5A {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion05_5A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To what degree was attending this feedback interview a source of added value for you?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion05_5A_51A_511 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion05_5A_51A_511", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To what degree were you given insight into the steps taken by the coachee within the context of the coaching path? and the results achieved?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion05_5A_51A_512 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion05_5A_51A_512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any other comments about the feedback interview?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion05_5A_51A_513 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion05_5A_51A_513", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What comments have been made to you about the feedback interview?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion05_5A_51B_511 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion05_5A_51B_511", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to be present in the future?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion05_5A_51B_512 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion05_5A_51B_512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like there to be a feedback interview in the future?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion05_5B {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion05_5B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What form did the feedback you received in the course of the coaching plan take?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion06 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What form did the feedback you received upon completion of the coaching plan take?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion07 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What did you appreciate about this feedback?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion08 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With regard to feedback, what would you expect to see done differently or to a greater degree?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion09 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you feel that the goal set at the start of the coaching plan has been achieved?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion10 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the current situation with regard to what was achieved? Do you feel that further support is worthwhile? Is a follow-up possible/desirable?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion10_10A {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion10_10A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why might that be the case in your opinion? What work still has to be done and by whom? How should we proceed?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion10_10B {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion10_10B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has the coachee given you any feedback with regard to the coaching plan? If so, what?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion11 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you satisfied with the service of the client assistants?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion12 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you satisfied with the process of invoicing?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion13 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have specific recommendations to improve our coaching?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion14 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are there any other comments you would like to make?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion15 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you advise other coworkers or colleagues to work with a coach of Quintessence?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion16 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion16_16A {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion16_16A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why not?.
        /// </summary>
        internal static string EvaluationFormCoachingQuestion16_16B {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingQuestion16_16B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prior information about coaching.
        /// </summary>
        internal static string EvaluationFormCoachingTitleBlock1 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingTitleBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intake interview.
        /// </summary>
        internal static string EvaluationFormCoachingTitleBlock2 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingTitleBlock2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback interview.
        /// </summary>
        internal static string EvaluationFormCoachingTitleBlock3 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingTitleBlock3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coaching interviews and (interim) reports.
        /// </summary>
        internal static string EvaluationFormCoachingTitleBlock4 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingTitleBlock4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string EvaluationFormCoachingTitleBlock5 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingTitleBlock5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation/Follow-up.
        /// </summary>
        internal static string EvaluationFormCoachingTitleBlock6 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingTitleBlock6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions/recommendations.
        /// </summary>
        internal static string EvaluationFormCoachingTitleBlock7 {
            get {
                return ResourceManager.GetString("EvaluationFormCoachingTitleBlock7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Quintessence Consulting we constantly work to improve the quality of our service. With that in mind we would like to ask you some questions about the quality of the consulting services Quintessence recently provided you with..
        /// </summary>
        internal static string EvaluationFormCustomProjectsIntroText {
            get {
                return ResourceManager.GetString("EvaluationFormCustomProjectsIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To what degree do you feel that the goal set at the beginning of the partnership was achieved? What has been achieved and what has not..
        /// </summary>
        internal static string EvaluationFormCustomProjectsQuestion01 {
            get {
                return ResourceManager.GetString("EvaluationFormCustomProjectsQuestion01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the current situation with regard to what has been achieved? Does the project arouse interest and do you build on it? Do you feel that further support is worthwhile? Is a follow-up possible/desirable?.
        /// </summary>
        internal static string EvaluationFormCustomProjectsQuestion02 {
            get {
                return ResourceManager.GetString("EvaluationFormCustomProjectsQuestion02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the project does/did not proceed as expected, what do you feel is the reason? What work still has to be done and by whom? How should we proceed?.
        /// </summary>
        internal static string EvaluationFormCustomProjectsQuestion03 {
            get {
                return ResourceManager.GetString("EvaluationFormCustomProjectsQuestion03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How did you find the process at the time and what is your general impression of it now, looking back?.
        /// </summary>
        internal static string EvaluationFormCustomProjectsQuestion04 {
            get {
                return ResourceManager.GetString("EvaluationFormCustomProjectsQuestion04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are your thoughts on how the project was communicated and supervised?.
        /// </summary>
        internal static string EvaluationFormCustomProjectsQuestion05 {
            get {
                return ResourceManager.GetString("EvaluationFormCustomProjectsQuestion05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are your thoughts on the participants? Did we invite the right people to take part? Were they able to make a substantive contribution? Were they able to gain support? Was everyone on board from the start? Did everyone stay on board?.
        /// </summary>
        internal static string EvaluationFormCustomProjectsQuestion06 {
            get {
                return ResourceManager.GetString("EvaluationFormCustomProjectsQuestion06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How did you experience the guidance and support during the workshops (speed, standard, structure, responses to difficult questions, material)?.
        /// </summary>
        internal static string EvaluationFormCustomProjectsQuestion07 {
            get {
                return ResourceManager.GetString("EvaluationFormCustomProjectsQuestion07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an adjustment was made, was it the right response at the right time and was it done correctly?.
        /// </summary>
        internal static string EvaluationFormCustomProjectsQuestion08 {
            get {
                return ResourceManager.GetString("EvaluationFormCustomProjectsQuestion08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are your thoughts on how the content and process were communicated to the steering group (clear, timely, relevant)? How was the support of the steering group?.
        /// </summary>
        internal static string EvaluationFormCustomProjectsQuestion09 {
            get {
                return ResourceManager.GetString("EvaluationFormCustomProjectsQuestion09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did we properly understand your demand?.
        /// </summary>
        internal static string EvaluationFormCustomProjectsQuestion10 {
            get {
                return ResourceManager.GetString("EvaluationFormCustomProjectsQuestion10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Were we sufficiently reachable and available?.
        /// </summary>
        internal static string EvaluationFormCustomProjectsQuestion11 {
            get {
                return ResourceManager.GetString("EvaluationFormCustomProjectsQuestion11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could you get hold of us when you needed to (to ask questions, share concerns)?.
        /// </summary>
        internal static string EvaluationFormCustomProjectsQuestion12 {
            get {
                return ResourceManager.GetString("EvaluationFormCustomProjectsQuestion12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Were you given good material support?.
        /// </summary>
        internal static string EvaluationFormCustomProjectsQuestion13 {
            get {
                return ResourceManager.GetString("EvaluationFormCustomProjectsQuestion13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did invoicing go smoothly during the project?.
        /// </summary>
        internal static string EvaluationFormCustomProjectsQuestion14 {
            get {
                return ResourceManager.GetString("EvaluationFormCustomProjectsQuestion14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What changes would you like to see next time?.
        /// </summary>
        internal static string EvaluationFormCustomProjectsQuestion15 {
            get {
                return ResourceManager.GetString("EvaluationFormCustomProjectsQuestion15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result/product.
        /// </summary>
        internal static string EvaluationFormCustomProjectsTitleBlock1 {
            get {
                return ResourceManager.GetString("EvaluationFormCustomProjectsTitleBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string EvaluationFormCustomProjectsTitleBlock2 {
            get {
                return ResourceManager.GetString("EvaluationFormCustomProjectsTitleBlock2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working relationship with project team/steering group/client assistants.
        /// </summary>
        internal static string EvaluationFormCustomProjectsTitleBlock3 {
            get {
                return ResourceManager.GetString("EvaluationFormCustomProjectsTitleBlock3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The evaluation has been succesfully submitted. Quintessence thanks you for your cooperation..
        /// </summary>
        internal static string FinalText {
            get {
                return ResourceManager.GetString("FinalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you.
        /// </summary>
        internal static string FinalTitle {
            get {
                return ResourceManager.GetString("FinalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antwerp | Ghent | Brussels.
        /// </summary>
        internal static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        internal static string IntroLabel {
            get {
                return ResourceManager.GetString("IntroLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code:.
        /// </summary>
        internal static string LoginCodeLabel {
            get {
                return ResourceManager.GetString("LoginCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the 6-digit code you have received by e-mail..
        /// </summary>
        internal static string LoginIntroText {
            get {
                return ResourceManager.GetString("LoginIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string LoginOkButton {
            get {
                return ResourceManager.GetString("LoginOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        internal static string Neutral {
            get {
                return ResourceManager.GetString("Neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not applicable.
        /// </summary>
        internal static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satisfied.
        /// </summary>
        internal static string Satisfied {
            get {
                return ResourceManager.GetString("Satisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show characters.
        /// </summary>
        internal static string ShowCharacters {
            get {
                return ResourceManager.GetString("ShowCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To what degree....
        /// </summary>
        internal static string ToWhatDegree {
            get {
                return ResourceManager.GetString("ToWhatDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very dissatisfied.
        /// </summary>
        internal static string VeryDissatisfied {
            get {
                return ResourceManager.GetString("VeryDissatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very satisfied.
        /// </summary>
        internal static string VerySatisfied {
            get {
                return ResourceManager.GetString("VerySatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
