//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quintessence.QJobService.JobDefinitions.TeamLeaderReplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmReplicationAssociate
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> UserGroupId { get; set; }
        public string TeamLeaderName { get; set; }
        public Nullable<int> TeamLeaderId { get; set; }
        public int SyncVersion { get; set; }
        public Nullable<System.DateTime> LastSyncedUtc { get; set; }
    }
}
