//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quintessence.QJobService.JobDefinitions.TeamLeaderReplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmReplicationEmail
    {
        public int Id { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public string ContactName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string DirectPhone { get; set; }
        public string MobilePhone { get; set; }
        public int SyncVersion { get; set; }
        public Nullable<System.DateTime> LastSyncedUtc { get; set; }
    }
}
