//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quintessence.QJobService.JobDefinitions.SuperOfficeReplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmReplicationProject
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> AssociateId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<int> ProjectStatusId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> BookyearFrom { get; set; }
        public Nullable<System.DateTime> BookyearTo { get; set; }
        public Nullable<int> TeamLeaderId { get; set; }
        public Nullable<System.DateTime> LastSyncedUtc { get; set; }
        public int SyncVersion { get; set; }
        public Nullable<int> SuperOfficeId { get; set; }
    }
}
