//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quintessence.QJobService.JobDefinitions.SuperOfficeReplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmReplicationProjectStatusMapping
    {
        public int Id { get; set; }
        public string SourceValue { get; set; }
        public int TargetId { get; set; }
    }
}
