//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quintessence.QJobService.JobDefinitions.SuperOfficeReplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmReplicationSuperOfficeEventErrorLog
    {
        public int Id { get; set; }
        public int CrmReplicationSuperOfficeEventId { get; set; }
        public System.DateTime LogDateUtc { get; set; }
        public string Info { get; set; }
    }
}
