//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quintessence.QJobService.JobDefinitions.SuperOfficeReplication.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuintessenceEntities : DbContext
    {
        public QuintessenceEntities()
            : base("name=QuintessenceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CrmReplicationAppointment> CrmReplicationAppointments { get; set; }
        public virtual DbSet<CrmReplicationAppointmentTaskMapping> CrmReplicationAppointmentTaskMappings { get; set; }
        public virtual DbSet<CrmReplicationAppointmentTimesheet> CrmReplicationAppointmentTimesheets { get; set; }
        public virtual DbSet<CrmReplicationAppointmentTraining> CrmReplicationAppointmentTrainings { get; set; }
        public virtual DbSet<CrmReplicationAssociate> CrmReplicationAssociates { get; set; }
        public virtual DbSet<CrmReplicationContact> CrmReplicationContacts { get; set; }
        public virtual DbSet<CrmReplicationEmail> CrmReplicationEmails { get; set; }
        public virtual DbSet<CrmReplicationEmailAssociate> CrmReplicationEmailAssociates { get; set; }
        public virtual DbSet<CrmReplicationJob> CrmReplicationJobs { get; set; }
        public virtual DbSet<CrmReplicationPerson> CrmReplicationPersons { get; set; }
        public virtual DbSet<CrmReplicationProject> CrmReplicationProjects { get; set; }
        public virtual DbSet<CrmReplicationProjectStatu> CrmReplicationProjectStatus { get; set; }
        public virtual DbSet<CrmReplicationProjectStatusMapping> CrmReplicationProjectStatusMappings { get; set; }
        public virtual DbSet<CrmReplicationSetting> CrmReplicationSettings { get; set; }
        public virtual DbSet<CrmReplicationSuperOfficeEventErrorLog> CrmReplicationSuperOfficeEventErrorLogs { get; set; }
        public virtual DbSet<CrmReplicationUserGroup> CrmReplicationUserGroups { get; set; }
        public virtual DbSet<CrmReplicationJobHistory> CrmReplicationJobHistories { get; set; }
        public virtual DbSet<CrmReplicationSuperOfficeEvent> CrmReplicationSuperOfficeEvents { get; set; }
        public virtual DbSet<Project2CrmProject> Project2CrmProject { get; set; }
        public virtual DbSet<Office> Offices { get; set; }
    }
}
