insert into dbo.office(shortname, fullname)values('ON', 'Online')
declare @officeId INT = (select top(1) id from dbo.office where ShortName = 'ON')
insert into dbo.AssessmentRoom(Id, Name, OfficeId, Audit_CreatedOn, Audit_CreatedBy)values(newid(), 'Room 1', @officeId, getdate(), 'Script')
insert into dbo.AssessmentRoom(Id, Name, OfficeId, Audit_CreatedOn, Audit_CreatedBy)values(newid(), 'Room 2', @officeId, getdate(), 'Script')
insert into dbo.AssessmentRoom(Id, Name, OfficeId, Audit_CreatedOn, Audit_CreatedBy)values(newid(), 'Room 3', @officeId, getdate(), 'Script')
insert into dbo.AssessmentRoom(Id, Name, OfficeId, Audit_CreatedOn, Audit_CreatedBy)values(newid(), 'Room 4', @officeId, getdate(), 'Script')
insert into dbo.AssessmentRoom(Id, Name, OfficeId, Audit_CreatedOn, Audit_CreatedBy)values(newid(), 'Room 5', @officeId, getdate(), 'Script')
insert into dbo.AssessmentRoom(Id, Name, OfficeId, Audit_CreatedOn, Audit_CreatedBy)values(newid(), 'Room 6', @officeId, getdate(), 'Script')
insert into dbo.AssessmentRoom(Id, Name, OfficeId, Audit_CreatedOn, Audit_CreatedBy)values(newid(), 'Room 7', @officeId, getdate(), 'Script')
insert into dbo.AssessmentRoom(Id, Name, OfficeId, Audit_CreatedOn, Audit_CreatedBy)values(newid(), 'Room 8', @officeId, getdate(), 'Script')
insert into dbo.AssessmentRoom(Id, Name, OfficeId, Audit_CreatedOn, Audit_CreatedBy)values(newid(), 'Room 9', @officeId, getdate(), 'Script')
insert into dbo.AssessmentRoom(Id, Name, OfficeId, Audit_CreatedOn, Audit_CreatedBy)values(newid(), 'Room 10', @officeId, getdate(), 'Script')
insert into dbo.AssessmentRoom(Id, Name, OfficeId, Audit_CreatedOn, Audit_CreatedBy)values(newid(), 'Room 11', @officeId, getdate(), 'Script')
insert into dbo.AssessmentRoom(Id, Name, OfficeId, Audit_CreatedOn, Audit_CreatedBy)values(newid(), 'Room 12', @officeId, getdate(), 'Script')
insert into dbo.AssessmentRoom(Id, Name, OfficeId, Audit_CreatedOn, Audit_CreatedBy)values(newid(), 'Room 13', @officeId, getdate(), 'Script')
insert into dbo.AssessmentRoom(Id, Name, OfficeId, Audit_CreatedOn, Audit_CreatedBy)values(newid(), 'Room 14', @officeId, getdate(), 'Script')
insert into dbo.AssessmentRoom(Id, Name, OfficeId, Audit_CreatedOn, Audit_CreatedBy)values(newid(), 'Room 15', @officeId, getdate(), 'Script')
insert into dbo.AssessmentRoom(Id, Name, OfficeId, Audit_CreatedOn, Audit_CreatedBy)values(newid(), 'Room 16', @officeId, getdate(), 'Script')
insert into dbo.AssessmentRoom(Id, Name, OfficeId, Audit_CreatedOn, Audit_CreatedBy)values(newid(), 'Room 17', @officeId, getdate(), 'Script')
insert into dbo.AssessmentRoom(Id, Name, OfficeId, Audit_CreatedOn, Audit_CreatedBy)values(newid(), 'Room 18', @officeId, getdate(), 'Script')
insert into dbo.AssessmentRoom(Id, Name, OfficeId, Audit_CreatedOn, Audit_CreatedBy)values(newid(), 'Room 19', @officeId, getdate(), 'Script')
insert into dbo.AssessmentRoom(Id, Name, OfficeId, Audit_CreatedOn, Audit_CreatedBy)values(newid(), 'Room 20', @officeId, getdate(), 'Script')