//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quintessence.QJobService.JobDefinitions.SuperOfficeDuplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Id { get; set; }
        public int AppointmentId { get; set; }
        public Nullable<int> MotherId { get; set; }
        public string Type { get; set; }
        public string Associate { get; set; }
        public string AssociateFullName { get; set; }
        public Nullable<int> AssociatePersonId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> SaleId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> DurationMinutes { get; set; }
        public string Text { get; set; }
        public Nullable<bool> Completed { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string Language { get; set; }
        public string Email { get; set; }
        public string Code { get; set; }
        public Nullable<bool> Reservation { get; set; }
        public string Location { get; set; }
        public System.DateTime LastSyncedUtc { get; set; }
    }
}
