//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quintessence.QJobService.JobDefinitions.SuperOfficeDuplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Id { get; set; }
        public int ContactId { get; set; }
        public string Name { get; set; }
        public string StreetAddressLine1 { get; set; }
        public string PostAddressLine1 { get; set; }
        public string PostAddressZip { get; set; }
        public string PostAddressCity { get; set; }
        public string Country { get; set; }
        public string ContactPhone { get; set; }
        public string ContactFax { get; set; }
        public string UrlAddress { get; set; }
        public string EmailAddress { get; set; }
        public string ContactAssociateFullName { get; set; }
        public Nullable<int> ContactAssociatePersonId { get; set; }
        public string Category { get; set; }
        public string Business { get; set; }
        public string OrgNr { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<bool> Stop { get; set; }
        public Nullable<bool> ContactNoMail { get; set; }
        public string Assistent { get; set; }
        public string FidelisationNorm { get; set; }
        public Nullable<bool> FocusList { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime LastSyncedUtc { get; set; }
    }
}
