//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quintessence.QJobService.JobDefinitions.SuperOfficeDuplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuplicationJobHistory
    {
        public System.Guid Id { get; set; }
        public string JobName { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> Succeeded { get; set; }
        public string Info { get; set; }
    }
}
