//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quintessence.QJobService.JobDefinitions.SuperOfficeDuplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int ContactId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string MrMrs { get; set; }
        public string Title { get; set; }
        public string EmailAddress { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> Retired { get; set; }
        public Nullable<bool> Inside { get; set; }
        public Nullable<bool> Nps { get; set; }
        public Nullable<bool> CommercialEmail { get; set; }
        public System.DateTime LastSyncedUtc { get; set; }
    }
}
