//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quintessence.QJobService.JobDefinitions.SuperOfficeDuplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMember
    {
        public int Id { get; set; }
        public int ProjectMemberId { get; set; }
        public int ProjectId { get; set; }
        public int PersonId { get; set; }
        public Nullable<int> ProjectMemberTypeId { get; set; }
        public string ProjectMemberTypeName { get; set; }
        public System.DateTime LastSyncedUtc { get; set; }
    }
}
