//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quintessence.QJobService.JobDefinitions.SuperOfficeDuplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Id { get; set; }
        public int SaleId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string Text { get; set; }
        public Nullable<int> PersonId { get; set; }
        public string AssociateId { get; set; }
        public string AssociateFullName { get; set; }
        public string Type { get; set; }
        public string Stage { get; set; }
        public string SaleStatus { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public string Source { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> Earning { get; set; }
        public string SaleText { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime LastSyncedUtc { get; set; }
    }
}
