//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quintessence.QJobService.JobDefinitions.SuperOfficeDuplication.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SuperOfficeEntities : DbContext
    {
        public SuperOfficeEntities()
            : base("name=SuperOfficeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DuplicationErrorLog> DuplicationErrorLogs { get; set; }
        public virtual DbSet<DuplicationJobHistory> DuplicationJobHistories { get; set; }
        public virtual DbSet<DuplicationSetting> DuplicationSettings { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<ProjectMember> ProjectMembers { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
    
        public virtual int TruncateDuplicationTables()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TruncateDuplicationTables");
        }
    }
}
