CREATE TABLE [dbo].[ActivityDetailTrainingCandidate](
	[Id]								UNIQUEIDENTIFIER		NOT NULL,
	[ActivityDetailTrainingId]			UNIQUEIDENTIFIER		NOT NULL,
	[CandidateId]						UNIQUEIDENTIFIER		NOT NULL,
	[ContactId]							INT						NOT NULL,
	[CrmAppointmentId]					INT						NOT NULL,
	[InvoiceAmount]						DECIMAL(18,2)			NULL,
	[InvoiceStatusCode]					INT						NOT NULL,
	[InvoicedDate]						DATETIME				NULL,
	[IsCancelled]						BIT						NOT NULL	DEFAULT 0,
	[CancelledDate]						DATETIME				NULL,
	[CancelledReason]					NVARCHAR(MAX)			NULL,
	[Audit_CreatedBy]					NVARCHAR(MAX)			NOT NULL	DEFAULT (suser_sname()),
	[Audit_CreatedOn]					DATETIME				NOT NULL	DEFAULT GETDATE(),
	[Audit_ModifiedBy]					NVARCHAR(MAX)			NULL,
	[Audit_ModifiedOn]					DATETIME				NULL,
	[Audit_DeletedBy]					NVARCHAR(MAX)			NULL,
	[Audit_DeletedOn]					DATETIME				NULL,
	[Audit_IsDeleted]					BIT						NOT NULL	DEFAULT 0,
	[Audit_VersionId]					UNIQUEIDENTIFIER		NOT NULL	DEFAULT NEWID()
)