//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire.
        /// </summary>
        internal static string AsIsQuestionnaireLegend {
            get {
                return ResourceManager.GetString("AsIsQuestionnaireLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your language.
        /// </summary>
        internal static string ChangeYourLanguage {
            get {
                return ResourceManager.GetString("ChangeYourLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your verification code.
        /// </summary>
        internal static string EnterVerificationCode {
            get {
                return ResourceManager.GetString("EnterVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antwerp | Ghent | Brussels.
        /// </summary>
        internal static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Least applicable.
        /// </summary>
        internal static string LeastApplicable {
            get {
                return ResourceManager.GetString("LeastApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most applicable.
        /// </summary>
        internal static string MostApplicable {
            get {
                return ResourceManager.GetString("MostApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to part 2.
        /// </summary>
        internal static string NextQuestionnaire {
            get {
                return ResourceManager.GetString("NextQuestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select 5 theorems that are the most appropriate and 5 theorems that are the least appropriate..
        /// </summary>
        internal static string PleaseFillInYourQuestionnaire {
            get {
                return ResourceManager.GetString("PleaseFillInYourQuestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select 5 theorems that are the most applicable in the future and 5 theorems that are the least applicable in the future..
        /// </summary>
        internal static string PleaseFillInYourQuestionnaireToBe {
            get {
                return ResourceManager.GetString("PleaseFillInYourQuestionnaireToBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select 5 theorems that are the least applicable. You have selected {0}..
        /// </summary>
        internal static string PleaseSelect5LeastApplicableTheorems {
            get {
                return ResourceManager.GetString("PleaseSelect5LeastApplicableTheorems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select 5 theorems that are the most applicable. You have selected {0}..
        /// </summary>
        internal static string PleaseSelecte5MostApplicableTheorems {
            get {
                return ResourceManager.GetString("PleaseSelecte5MostApplicableTheorems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already completed the questionnaire. We thank you for your cooperation!.
        /// </summary>
        internal static string QuestionnaireAlreadyCompleted {
            get {
                return ResourceManager.GetString("QuestionnaireAlreadyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The questionnaire has already been completed.
        /// </summary>
        internal static string QuestionnaireAlreadyCompletedLegend {
            get {
                return ResourceManager.GetString("QuestionnaireAlreadyCompletedLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to your questionnaire.
        /// </summary>
        internal static string ReturnToYourQuestionnaire {
            get {
                return ResourceManager.GetString("ReturnToYourQuestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Characters.
        /// </summary>
        internal static string ShowCharacters {
            get {
                return ResourceManager.GetString("ShowCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit questionnaire.
        /// </summary>
        internal static string SubmitQuestionnaire {
            get {
                return ResourceManager.GetString("SubmitQuestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have successfully processes your questionnaire.
        ///On behalf of the entire Quintessence-team, we thank you for your participation.&lt;br/&gt;
        ///Click on the icon below to download your results in .pdf.
        /// </summary>
        internal static string SuccessfullyProcessed {
            get {
                return ResourceManager.GetString("SuccessfullyProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were problems with your questionnaire.
        /// </summary>
        internal static string ThereWereProblemsWithYourQuestionnaire {
            get {
                return ResourceManager.GetString("ThereWereProblemsWithYourQuestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire for future situation.
        /// </summary>
        internal static string ToBeQuestionnaireLegend {
            get {
                return ResourceManager.GetString("ToBeQuestionnaireLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        internal static string VerificationTitle {
            get {
                return ResourceManager.GetString("VerificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Cultural Fit questionnaire. You will be presented with 2 lists of statements. On the first list, indicate 5 statements that are the most applicable to the current situation of your organization. Also select 5 statements which are the least applicable to your organization. After that you will be presented the exact same list with statements. Only here select the same amount of statements of which you want to be applicable to your organization. &lt;/br&gt;&lt;/br&gt;Click &quot;Start&quot; to continue..
        /// </summary>
        internal static string WelcomeBodyAsIsCustomer {
            get {
                return ResourceManager.GetString("WelcomeBodyAsIsCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welkom bij de cultuurvragenlijst. Deze vragenlijst gaat na wat voor u belangrijk is binnen een organisatie. De vragenlijst bestaat uit verschillende stellingen. U dient hierbij aan te vinken welke 5 stellingen het meest op u van toepassing zijn en welke 5 stellingen het minst op u van toepassing zijn. Wanneer u alles ingevuld heeft, heeft u de mogelijkheid om uw resultaten in PDF-vorm te downloaden, het is dan niet meer mogelijk om uw antwoorden te wijzigen. &lt;/br&gt;&lt;/br&gt;Klik op &quot;Start&quot; om te beginnen. [EN].
        /// </summary>
        internal static string WelcomeBodyAsIsParticipant {
            get {
                return ResourceManager.GetString("WelcomeBodyAsIsParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welkom bij de cultuurvragenlijst. Deze vragenlijst gaat na wat binnen uw organisatie belangrijk is. De vragenlijst bestaat uit  twee delen. Het eerste deel peilt naar wat momenteel binnen uw organisatie geldt. Het tweede deel gaat na naar welke richting de organisatie dient te evolueren. Elk deel bestaat uit verschillende stellingen. Bij deel 1 vinkt u aan welke 5 stellingen het meest op uw organisatie van toepassing zijn en welke 5 stellingen het minst op uw organisatie van toepassing zijn. Bij deel 2 gaat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WelcomeBodyAsIsToBe {
            get {
                return ResourceManager.GetString("WelcomeBodyAsIsToBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to process your questionnaire due to the following problem(s).
        /// </summary>
        internal static string WeWereUnableToProcessYourQuestionnaireDueToTheFollowingProblems {
            get {
                return ResourceManager.GetString("WeWereUnableToProcessYourQuestionnaireDueToTheFollowingProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect verification code.
        /// </summary>
        internal static string WrongVerificationCode {
            get {
                return ResourceManager.GetString("WrongVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your questionnaire.
        /// </summary>
        internal static string YourQuestionnaire {
            get {
                return ResourceManager.GetString("YourQuestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your questionnaire has been processed.
        /// </summary>
        internal static string YourQuestionnaireHasBeenProcessed {
            get {
                return ResourceManager.GetString("YourQuestionnaireHasBeenProcessed", resourceCulture);
            }
        }
    }
}
