
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'CrmReplicationUserGroup' AND TABLE_SCHEMA ='dbo' )
BEGIN
  ALTER TABLE [dbo].[CrmReplicationUserGroup]
  ADD CONSTRAINT PK_CrmReplicationUserGroup PRIMARY KEY(Id)
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'CrmReplicationProjectStatus' AND TABLE_SCHEMA ='dbo' )
BEGIN
  ALTER TABLE CrmReplicationProjectStatus
  ADD CONSTRAINT PK_CrmReplicationProjectStatus PRIMARY KEY(Id)
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'CrmReplicationProject' AND TABLE_SCHEMA ='dbo' )
BEGIN
  ALTER TABLE CrmReplicationProject
  ADD CONSTRAINT PK_CrmReplicationProject PRIMARY KEY(Id)
END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'CrmReplicationPerson' AND TABLE_SCHEMA ='dbo' )
BEGIN
  ALTER TABLE CrmReplicationPerson
  ADD CONSTRAINT PK_CrmReplicationPerson PRIMARY KEY(Id)
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'CrmReplicationJob' AND TABLE_SCHEMA ='dbo' )
BEGIN
  ALTER TABLE CrmReplicationJob
  ADD CONSTRAINT PK_CrmReplicationJob PRIMARY KEY(Id)
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'CrmReplicationJobHistory' AND TABLE_SCHEMA ='dbo' )
BEGIN
  ALTER TABLE CrmReplicationJobHistory
  ADD CONSTRAINT PK_CrmReplicationJobHistory PRIMARY KEY(Id)
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'CrmReplicationEmail' AND TABLE_SCHEMA ='dbo' )
BEGIN
  ALTER TABLE CrmReplicationEmail
  ADD CONSTRAINT PK_CrmReplicationEmail PRIMARY KEY(Id)
END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'CrmReplicationEmailAssociate' AND TABLE_SCHEMA ='dbo' )
BEGIN
  ALTER TABLE CrmReplicationEmailAssociate
  ADD CONSTRAINT PK_CrmReplicationEmailAssociate PRIMARY KEY(Id)
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'CrmReplicationContact' AND TABLE_SCHEMA ='dbo' )
BEGIN
  ALTER TABLE CrmReplicationContact
  ADD CONSTRAINT PK_CrmReplicationContact PRIMARY KEY(Id)
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'CrmReplicationAssociate' AND TABLE_SCHEMA ='dbo' )
BEGIN
  ALTER TABLE CrmReplicationAssociate
  ADD CONSTRAINT PK_CrmReplicationAssociate PRIMARY KEY(Id)
END
GO

ALTER TABLE [dbo].[CrmReplicationAppointmentTraining]
ALTER COLUMN Id INT NOT NULL
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'CrmReplicationAppointmentTraining' AND TABLE_SCHEMA ='dbo' )
BEGIN
  ALTER TABLE CrmReplicationAppointmentTraining
  ADD CONSTRAINT PK_CrmReplicationAppointmentTraining PRIMARY KEY(Id)
END
GO

ALTER TABLE [dbo].[CrmReplicationAppointmentTimesheet]
ALTER COLUMN Id INT NOT NULL
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'CrmReplicationAppointmentTimesheet' AND TABLE_SCHEMA ='dbo' )
BEGIN
  ALTER TABLE CrmReplicationAppointmentTimesheet
  ADD CONSTRAINT PK_CrmReplicationAppointmentTimesheet PRIMARY KEY(Id)
END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'CrmReplicationAppointment' AND TABLE_SCHEMA ='dbo' )
BEGIN
  ALTER TABLE CrmReplicationAppointment
  ADD CONSTRAINT PK_CrmReplicationAppointment PRIMARY KEY(Id)
END
GO



