USE [TeamLeader]
GO

-- DuplicationSettings
CREATE TABLE [dbo].[DuplicationSettings]
(
	[Id] [int] NOT NULL,
	[Key] [nvarchar](max) NOT NULL,
	[Value] [nvarchar](max) NULL
    CONSTRAINT [PK_DuplicationSettings] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

-- DuplicationSettings
INSERT INTO dbo.DuplicationSettings ( Id, [Key], Value )
VALUES  ( 1, -- Id - int
          N'TeamLeaderAPI_Group',
          N'16961'
          )
GO

INSERT INTO dbo.DuplicationSettings ( Id, [Key], Value )
VALUES  ( 2, -- Id - int
          N'TeamLeaderAPI_Key',
          N'S7CFlCOQeMxI7nfPmeXdQ7ZIdB7eDNtmKWRWpwCt8026e8MrczvSwkrALpEf2YrDK9pZvSjuIcrNa34cspVPzcfasKglyxO9x4ZSN9cmctZcnTfF90ly3qzl1Fwp3bpq6f9KecWgvMjJwoeveqU7GjjxPGNJH30E8Zed11knDtWZI1lMh5KOfUcUqQuXJkrI9wL1nWfQ'
          )
GO

INSERT INTO dbo.DuplicationSettings ( Id, [Key], Value )
VALUES  ( 3, -- Id - int
          N'TeamLeaderAPI_BaseUrl',
          N'https://www.teamleader.be/api'
          )
GO

INSERT INTO dbo.DuplicationSettings ( Id, [Key], Value )
VALUES  ( 4, -- Id - int
          N'TeamLeaderDuplicator_DuplicatorBatchSize',
          N'100'
          )
GO

-------------------------------------------------------------------------------------------------------------

CREATE TABLE [User]
(
	Id INT NOT NULL,
	TeamLeaderId INT NOT NULL,
	Name NVARCHAR(128) NULL,
	Email NVARCHAR(128) NULL,
	Gsm NVARCHAR(64) NULL,
	Telephone NVARCHAR(64) NULL,
	Title NVARCHAR(128) NULL,
	LastSyncedUtc DATETIME NOT NULL
    CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE Contact
(
	Id INT NOT NULL,
	TeamLeaderId INT NOT NULL,
	FirstName NVARCHAR(64) NULL,
	LastName NVARCHAR(128) NULL,
	Street NVARCHAR(128) NULL,
	Number NVARCHAR(10) NULL,
	Zipcode NVARCHAR(10) NULL,
	City NVARCHAR(128) NULL,
	Country NVARCHAR(128) NULL,
	Website NVARCHAR(128) NULL,
	Email NVARCHAR(128) NULL,
	Gsm NVARCHAR(64) NULL,
	Telephone NVARCHAR(64) NULL,
	Fax NVARCHAR(64) NULL,
	Gender VARCHAR(2) NULL,
	LanguageCode VARCHAR(2) NULL,
	DateAdded DATETIME NULL,
	DateEdited DATETIME NULL,
	Status NVARCHAR(64) NULL,
	LegacyId INT NULL,
	Positie NVARCHAR(128) NULL,
	FormerEmployee NVARCHAR(128) NULL,
	LastSyncedUtc DATETIME NOT NULL
    CONSTRAINT [PK_Contact] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [Company]
(
	Id INT NOT NULL,
	TeamLeaderId INT NOT NULL,
	Name NVARCHAR(128) NULL,
	TaxCode NVARCHAR(32) NULL,
	BusinessType NVARCHAR(64) NULL,
	Street NVARCHAR(128) NULL,
	Number NVARCHAR(32) NULL,
	ZipCode NVARCHAR(10) NULL,
	City NVARCHAR(128) NULL,
	Country NVARCHAR(128) NULL,
	Website NVARCHAR(128) NULL,
	Email NVARCHAR(128) NULL,
	Telephone NVARCHAR(64) NULL,
	Fax NVARCHAR(64) NULL,
	Iban NVARCHAR(32) NULL,
	Bic NVARCHAR(12) NULL,
	LanguageCode VARCHAR(2) NULL,
	Afdeling NVARCHAR(128) NULL,
	AccountManagerId INT NULL,
	AccountManagerTwo NVARCHAR(128) NULL,
	Assistent NVARCHAR(64) NULL,
	DateAdded DATETIME NULL,
	DateEdited DATETIME NULL,
	Status NVARCHAR(64) NULL,
	Business NVARCHAR(128) NULL,
	FidelisatieNorm NVARCHAR(128)  NULL,
	FocusList BIT NULL,
	LinkedInProfile NVARCHAR(MAX) NULL,
	Sector NVARCHAR(128) NULL,
	LastSyncedUtc DATETIME NOT NULL
    CONSTRAINT [PK_Company] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [Project]
(
	Id INT NOT NULL,
	TeamLeaderId INT NOT NULL,
	Title NVARCHAR(128) NULL,
	Phase NVARCHAR(64) NULL,
	StartDate DATETIME NULL,
	LegacyId INT NULL,
	BoekJaar NVARCHAR(32) NULL,
	LastSyncedUtc DATETIME NOT NULL
    CONSTRAINT [PK_Project] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [Task]
(
	Id INT NOT NULL,
	TeamLeaderId INT NOT NULL,
	[Description] NVARCHAR(MAX) NULL,
	FirstName NVARCHAR(64) NULL,
	LastName NVARCHAR(128) NULL,
	Intern NVARCHAR(128) NULL,
	Klant NVARCHAR(128) NULL,
	Overige NVARCHAR(128) NULL,
	ProjectId INT NULL,
	Sales NVARCHAR(128) NULL,
	Reservatie INT NULL,
	Code NVARCHAR(16) NULL,
	LanguageCode VARCHAR(2) NULL,
	Gender VARCHAR(2) NULL,
	DueDate DATETIME NULL,
	ResponsibleUserId INT NULL,
	LastSyncedUtc DATETIME NOT NULL
    CONSTRAINT [PK_Task] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [TimeTracking]
(
	Id INT NOT NULL,
	TeamLeaderId INT NOT NULL,
	ProjectId INT NULL,
	ProjectTitle NVARCHAR(128) NULL,
	UserId INT NULL,
	EmployeeName NVARCHAR(128) NULL,
	StartDate DATETIME NULL,
	EndDate DATETIME NULL,
	ContactId INT NULL,
	ContactName NVARCHAR(128) NULL,
	CompanyId INT NULL,
	CompanyName NVARCHAR(128) NULL,
	[Description] NVARCHAR(MAX) NULL,
	Category NVARCHAR(128) NULL,

	LastSyncedUtc DATETIME NOT NULL
    CONSTRAINT [PK_TimeTracking] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [Deal]
(
	Id INT NOT NULL,
	TeamLeaderId INT NOT NULL,
	Title NVARCHAR(128) NULL,
	CustomerName NVARCHAR(128) NULL,
	QuatationNr INT NULL,
	TotalPriceExclVat DECIMAL(10,2) NULL,
	Probability INT NULL,
	PhaseId INT NULL,
	ResponsibleUserId INT NULL,
	EntryDate DATETIME NULL,
	LatestActivityDate DATETIME NULL,
	CloseDate DATETIME NULL,
	DateLost DATETIME NULL,
	ReasonRefused NVARCHAR(MAX) NULL,
	SourceId INT NULL,
	LastSyncedUtc DATETIME NOT NULL
    CONSTRAINT [PK_Deal] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [DealSource]
(
	Id INT NOT NULL,
	TeamLeaderId INT NOT NULL,
	Name NVARCHAR(128) NULL,
	LastSyncedUtc DATETIME NOT NULL
    CONSTRAINT [PK_DealSource] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [DealPhase]
(
	Id INT NOT NULL,
	TeamLeaderId INT NOT NULL,
	Name NVARCHAR(128) NULL,
	LastSyncedUtc DATETIME NOT NULL
    CONSTRAINT [PK_DealPhase] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [Call]
(
	Id INT NOT NULL,
	TeamLeaderId INT NOT NULL,
	DueDate DATETIME NULL,
	UserId INT NULL,
	UserName NVARCHAR(128) NULL,
	CallDateTime DATETIME NULL,
	Telephone NVARCHAR(64) NULL,
	Gsm NVARCHAR(64) NULL,
	RelatedProjectId INT NULL,
	RelatedMilestoneId INT NULL,
	ForType NVARCHAR(64) NULL,
	ForId INT NULL,
	Klant NVARCHAR(128) NULL,
	Intern NVARCHAR(128) NULL,
	Sales NVARCHAR(128) NULL,
	LastSyncedUtc DATETIME NOT NULL
    CONSTRAINT [PK_Call] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [Meeting]
(
	Id INT NOT NULL,
	TeamLeaderId INT NOT NULL,
	DurationMinutes INT NULL,
	DateTimeStamp DATETIME NULL,
	MeetingDate DATETIME NULL,
	RelatedProjectId INT NULL,
	RelatedMilestoneId INT NULL,

	Title NVARCHAR(128) NULL,
	CreatorId INT NULL,
	CancellerId INT NULL,
	Afwezig NVARCHAR(128) NULL,
	Bedrijf NVARCHAR(128) NULL,
	Klant NVARCHAR(128) NULL,
	Intern NVARCHAR(128) NULL,
	Sales NVARCHAR(128) NULL,
	Location NVARCHAR(256) NULL,
	LastSyncedUtc DATETIME NOT NULL
    CONSTRAINT [PK_Meeting] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [MeetingUser]
(
	Id INT NOT NULL,
	MeetingId INT NOT NULL,
	UserTeamLeaderId INT NOT NULL,
	UserName NVARCHAR(128) NULL,
    CONSTRAINT [PK_MeetingUser] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


ALTER TABLE [dbo].[MeetingUser]
	ADD CONSTRAINT [FK_MeetingUser_MeetingTeamLeaderId_Meeting_Id]
	FOREIGN KEY (MeetingId)
	REFERENCES [Meeting] (Id)
GO

CREATE TABLE [MeetingContact]
(
	Id INT NOT NULL,
	MeetingId INT NOT NULL,
	ContactTeamLeaderId INT NOT NULL,
	ContactName NVARCHAR(128) NULL,
    CONSTRAINT [PK_MeetingContact] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


ALTER TABLE [dbo].[MeetingContact]
	ADD CONSTRAINT [FK_MeetingContact_MeetingTeamLeaderId_Meeting_Id]
	FOREIGN KEY (MeetingId)
	REFERENCES [Meeting] (Id)
GO


CREATE TABLE [ContactCompany]
(
	Id INT NOT NULL,
	TeamLeaderId INT NOT NULL,
	ContactId INT NULL,
	CompanyId INT NULL,
	[Function] NVARCHAR(128) NULL,
	LastSyncedUtc DATETIME NOT NULL
    CONSTRAINT [PK_ContactCompany] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [PlannedTask]
(
	Id INT NOT NULL,
	TodoId INT NULL,
	StartDate DATETIME NULL,
	DurationMinutes INT NULL,
	UserId INT NULL,
	ProjectId INT NULL,
	LastSyncedUtc DATETIME NOT NULL
    CONSTRAINT [PK_PlannedTask] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [ContactProject]
(
	Id INT NOT NULL,
	ProjectTeamLeaderId INT NOT NULL,
	[Group] NVARCHAR(128) NULL,
	ObjectType NVARCHAR(64) NULL,
	ObjectId INT NULL,
	Name NVARCHAR(128) NULL,
	[Role] NVARCHAR(128) NULL,
	Telephone NVARCHAR(64) NULL,
	Email NVARCHAR(128) NULL,
	LastSyncedUtc DATETIME NOT NULL
    CONSTRAINT [PK_ContactProject] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [Product]
(
	Id INT NOT NULL,
	ExternalId INT NULL,
	Name NVARCHAR(128) NULL,
	Vat DECIMAL(10, 2) NULL,
	BookingAccount NVARCHAR(128) NULL,
	BookingAccountId INT NULL,
	Stock INT NULL,
	Price DECIMAL(10, 2) NULL,
	LastSyncedUtc DATETIME NOT NULL
    CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DuplicationErrorLog]
(
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[LogDateUtc] [datetime] NOT NULL,
	[Info] [nvarchar](max) NULL,
 CONSTRAINT [PK_DuplicationErrorLog] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[DuplicationJobHistory]
(
	[Id] [uniqueidentifier] NOT NULL,
	[JobName] NVARCHAR(128) NOT NULL,
	[StartDate] [datetime] NOT NULL,
	[EndDate] [datetime] NULL,
	[Succeeded] [bit] NULL,
	[Info] [nvarchar](max) NULL,
 CONSTRAINT [PK_DuplicationJobHistory] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO


----------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[TruncateDuplicationTables]
AS
BEGIN

	DELETE FROM  dbo.Call 
	DELETE FROM  dbo.Company
	DELETE FROM  dbo.Contact
	DELETE FROM  dbo.Company
	DELETE FROM  dbo.ContactCompany
	DELETE FROM  dbo.ContactProject
	DELETE FROM  dbo.Deal
	DELETE FROM  dbo.DealPhase
	DELETE FROM  dbo.DealSource
	DELETE FROM  dbo.MeetingUser
	DELETE FROM  dbo.MeetingContact
	DELETE FROM  dbo.Meeting
	DELETE FROM  dbo.PlannedTask
	DELETE FROM  dbo.Project
	DELETE FROM  dbo.Task
	DELETE FROM  dbo.TimeTracking
	DELETE FROM  dbo.[User]

END
GO
