//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quintessence.QJobService.JobDefinitions.TeamLeaderDuplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call
    {
        public int Id { get; set; }
        public int TeamLeaderId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> CallDateTime { get; set; }
        public string Telephone { get; set; }
        public string Gsm { get; set; }
        public Nullable<int> RelatedProjectId { get; set; }
        public Nullable<int> RelatedMilestoneId { get; set; }
        public string ForType { get; set; }
        public Nullable<int> ForId { get; set; }
        public System.DateTime LastSyncedUtc { get; set; }
        public string Klant { get; set; }
        public string Intern { get; set; }
        public string Sales { get; set; }
    }
}
