//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quintessence.QJobService.JobDefinitions.TeamLeaderDuplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Id { get; set; }
        public int TeamLeaderId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Street { get; set; }
        public string Number { get; set; }
        public string Zipcode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string Gsm { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Gender { get; set; }
        public string LanguageCode { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateEdited { get; set; }
        public string Status { get; set; }
        public System.DateTime LastSyncedUtc { get; set; }
        public Nullable<int> LegacyId { get; set; }
        public string Positie { get; set; }
        public string FormerEmployee { get; set; }
    }
}
