//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quintessence.QJobService.JobDefinitions.TeamLeaderDuplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int Id { get; set; }
        public int TeamLeaderId { get; set; }
        public string Title { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> QuatationNr { get; set; }
        public Nullable<decimal> TotalPriceExclVat { get; set; }
        public Nullable<int> Probability { get; set; }
        public Nullable<int> PhaseId { get; set; }
        public Nullable<int> ResponsibleUserId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> LatestActivityDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<System.DateTime> DateLost { get; set; }
        public string ReasonRefused { get; set; }
        public Nullable<int> SourceId { get; set; }
        public System.DateTime LastSyncedUtc { get; set; }
    }
}
