//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quintessence.QJobService.JobDefinitions.TeamLeaderDuplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public Meeting()
        {
            this.MeetingContacts = new HashSet<MeetingContact>();
            this.MeetingUsers = new HashSet<MeetingUser>();
        }
    
        public int Id { get; set; }
        public int TeamLeaderId { get; set; }
        public Nullable<int> DurationMinutes { get; set; }
        public Nullable<System.DateTime> DateTimeStamp { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
        public Nullable<int> RelatedProjectId { get; set; }
        public Nullable<int> RelatedMilestoneId { get; set; }
        public string Title { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<int> CancellerId { get; set; }
        public string Afwezig { get; set; }
        public string Bedrijf { get; set; }
        public string Klant { get; set; }
        public string Intern { get; set; }
        public string Sales { get; set; }
        public System.DateTime LastSyncedUtc { get; set; }
        public string Location { get; set; }
    
        public virtual ICollection<MeetingContact> MeetingContacts { get; set; }
        public virtual ICollection<MeetingUser> MeetingUsers { get; set; }
    }
}
