//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quintessence.QJobService.JobDefinitions.TeamLeaderDuplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingContact
    {
        public int Id { get; set; }
        public int MeetingId { get; set; }
        public int ContactTeamLeaderId { get; set; }
        public string ContactName { get; set; }
    
        public virtual Meeting Meeting { get; set; }
    }
}
