//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quintessence.QJobService.JobDefinitions.TeamLeaderDuplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlannedTask
    {
        public int Id { get; set; }
        public Nullable<int> TodoId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> DurationMinutes { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public System.DateTime LastSyncedUtc { get; set; }
    }
}
