//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quintessence.QJobService.JobDefinitions.TeamLeaderDuplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int Id { get; set; }
        public int TeamLeaderId { get; set; }
        public string Title { get; set; }
        public string Phase { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> LegacyId { get; set; }
        public string BoekJaar { get; set; }
        public System.DateTime LastSyncedUtc { get; set; }
    }
}
