//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quintessence.QJobService.JobDefinitions.TeamLeaderDuplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public int TeamLeaderId { get; set; }
        public string Description { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Intern { get; set; }
        public string Klant { get; set; }
        public string Overige { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string Sales { get; set; }
        public Nullable<int> Reservatie { get; set; }
        public string Code { get; set; }
        public string LanguageCode { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> ResponsibleUserId { get; set; }
        public System.DateTime LastSyncedUtc { get; set; }
        public bool IsFinished { get; set; }
    }
}
