//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quintessence.QJobService.JobDefinitions.TeamLeaderDuplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTracking
    {
        public int Id { get; set; }
        public int TeamLeaderId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ProjectTitle { get; set; }
        public Nullable<int> UserId { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ContactId { get; set; }
        public string ContactName { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public System.DateTime LastSyncedUtc { get; set; }
        public string RelatedToObjectType { get; set; }
        public Nullable<int> RelatedToObjectId { get; set; }
    }
}
