//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quintessence.QJobService.JobDefinitions.TeamLeaderDuplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public int TeamLeaderId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Gsm { get; set; }
        public string Telephone { get; set; }
        public string Title { get; set; }
        public System.DateTime LastSyncedUtc { get; set; }
    }
}
