CREATE TABLE [dbo].[Proposal] (
    [Id]                  UNIQUEIDENTIFIER NOT NULL,
    [Name]                NVARCHAR (100)   NOT NULL,
    [Description]         TEXT             NULL,
    [ContactId]           INT              NOT NULL,
    [BusinessDeveloperId] UNIQUEIDENTIFIER NULL,
    [ExecutorId]          UNIQUEIDENTIFIER NULL,
    [DateReceived]        DATETIME         NULL,
    [Deadline]            DATETIME         NULL,
    [DateSent]            DATETIME         NULL,
    [DateWon]             DATETIME         NULL,
    [PriceEstimation]     DECIMAL (18, 2)  NULL,
    [Prognosis]           DECIMAL (18, 2)  NULL,
    [FinalBudget]         DECIMAL (18, 2)  NULL,
    [StatusCode]          INT              NOT NULL,
    [StatusReason]        TEXT             NULL,
    [WrittenProposal]     BIT              CONSTRAINT [DF_Proposal_WrittenProposal] DEFAULT ((0)) NOT NULL,
    [Audit_CreatedBy]     NVARCHAR (MAX)   CONSTRAINT [DF__tmp_ms_xx__Audit__30CE2BBB] DEFAULT (suser_sname()) NOT NULL,
    [Audit_CreatedOn]     DATETIME         CONSTRAINT [DF__tmp_ms_xx__Audit__31C24FF4] DEFAULT (getdate()) NOT NULL,
    [Audit_ModifiedBy]    NVARCHAR (MAX)   NULL,
    [Audit_ModifiedOn]    DATETIME         NULL,
    [Audit_DeletedBy]     NVARCHAR (MAX)   NULL,
    [Audit_DeletedOn]     DATETIME         NULL,
    [Audit_IsDeleted]     BIT              CONSTRAINT [DF__tmp_ms_xx__Audit__32B6742D] DEFAULT ((0)) NOT NULL,
    [Audit_VersionId]     UNIQUEIDENTIFIER CONSTRAINT [DF__tmp_ms_xx__Audit__33AA9866] DEFAULT (newid()) NOT NULL,
    CONSTRAINT [PK_Proposal] PRIMARY KEY NONCLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Project_BusinessDeveloper] FOREIGN KEY ([BusinessDeveloperId]) REFERENCES [dbo].[User] ([Id])
);

