CREATE TABLE [dbo].[EvaluationFormCoaching](
	[Id]								UNIQUEIDENTIFIER	NOT NULL, 
    [Question01]						NVARCHAR(MAX)		NULL,
    [Question02]						NVARCHAR(MAX)		NULL,
    [Question03]						BIT					NULL,
    [Question04A]						BIT					NULL,
    [Question04A_41A_411]				NVARCHAR(MAX)		NULL,
    [Question04A_41A_412]				NVARCHAR(MAX)		NULL,
    [Question04A_41A_413]				NVARCHAR(MAX)		NULL,
	[Question04A_41B_411]				NVARCHAR(MAX)		NULL,
    [Question04A_41B_412]				NVARCHAR(MAX)		NULL,
    [Question04B]						NVARCHAR(MAX)		NULL,
    [Question05]						BIT					NULL,
    [Question05_5A]						BIT					NULL,
    [Question05_5A_51A_511]				NVARCHAR(MAX)		NULL,
    [Question05_5A_51A_512]				NVARCHAR(MAX)		NULL,
    [Question05_5A_51A_513]				NVARCHAR(MAX)		NULL,
    [Question05_5A_51B_511]				NVARCHAR(MAX)		NULL,
    [Question05_5A_51B_512]				NVARCHAR(MAX)		NULL,
    [Question05_5B]						NVARCHAR(MAX)		NULL,
    [Question06]						NVARCHAR(MAX)		NULL,
    [Question07]						NVARCHAR(MAX)		NULL,
    [Question08]						NVARCHAR(MAX)		NULL,
    [Question09]						NVARCHAR(MAX)		NULL,
    [Question10]						BIT					NULL,
    [Question10_10A]					NVARCHAR(MAX)		NULL,
    [Question10_10B]					NVARCHAR(MAX)		NULL,
    [Question11]						NVARCHAR(MAX)		NULL,
    [Question12]						INT					NULL,
    [Question13]						INT					NULL,
    [Question14]						NVARCHAR(MAX)		NULL,
    [Question15]						NVARCHAR(MAX)		NULL,
	[Question16]						BIT					NULL,
    [Question16_16A]					NVARCHAR(MAX)		NULL,
    [Question16_16B]					NVARCHAR(MAX)		NULL							
)
GO
