CREATE TABLE [dbo].[EvaluationFormAcdc](
	[Id]								UNIQUEIDENTIFIER	NOT NULL, 
    [Question01]						INT					NULL,
    [Question02]						INT					NULL,
    [Question03]						INT					NULL,
    [Question04]						INT					NULL,
    [Question05]						INT					NULL,
    [Question06]						INT					NULL,
    [Question07]						INT					NULL,
    [Question08]						NVARCHAR(MAX)		NULL,
    [Question09]						NVARCHAR(MAX)		NULL,
    [Question10]						NVARCHAR(MAX)		NULL,
    [Question11]						BIT					NULL,
    [Question12]						BIT					NULL,
    [Question13]						BIT					NULL,
    [Question14]						BIT					NULL,
    [Question15]						BIT					NULL,
    [Question16]						BIT					NULL,
    [Question17]						BIT					NULL,
    [Question18]						NVARCHAR(MAX)		NULL,
    [Question19]						BIT					NULL,
    [Question19_19A]					NVARCHAR(MAX)		NULL,
    [Question19_19B]					NVARCHAR(MAX)		NULL,
    [Question20]						NVARCHAR(MAX)		NULL,
    [Question21]						NVARCHAR(MAX)		NULL,
    [Question22]						NVARCHAR(MAX)		NULL,
    [Question23]						NVARCHAR(MAX)		NULL,
    [Question24]						NVARCHAR(MAX)		NULL,
    [Question25]						NVARCHAR(MAX)		NULL,
    [Question26]						NVARCHAR(MAX)		NULL						
)
GO
