CREATE TABLE [dbo].[EvaluationForm](
	[Id]								UNIQUEIDENTIFIER	NOT NULL, 
    [CrmProjectId]						INT					NOT NULL,
    [FirstName]							NVARCHAR(MAX)		NOT NULL,
    [LastName]							NVARCHAR(MAX)		NOT NULL,
    [Gender]							CHAR(1)				NOT NULL,
    [Email]								NVARCHAR(MAX)		NOT NULL,
    [MailStatusTypeId]					INT					NOT NULL,
    [VerificationCode]					VARCHAR(6)			NOT NULL,
    [LanguageId]						INT					NOT NULL,
    [EvaluationFormTypeId]				INT					NOT NULL,
	[IsCompleted]						BIT					NOT NULL	DEFAULT 0,
	[Audit_CreatedBy]					NVARCHAR(MAX)		NOT NULL	DEFAULT (suser_sname()),
	[Audit_CreatedOn]					DATETIME			NOT NULL	DEFAULT GETDATE(),
	[Audit_ModifiedBy]					NVARCHAR(MAX)		NULL,
	[Audit_ModifiedOn]					DATETIME			NULL,
	[Audit_DeletedBy]					NVARCHAR(MAX)		NULL,
	[Audit_DeletedOn]					DATETIME			NULL,
	[Audit_IsDeleted]					BIT					NOT NULL	DEFAULT 0,
	[Audit_VersionId]					UNIQUEIDENTIFIER	NOT NULL	DEFAULT NEWID()
)