CREATE TABLE [dbo].[ProductsheetEntry] (
	[Id]						UNIQUEIDENTIFIER		NOT NULL,
	[Name]						NVARCHAR(MAX)			NOT NULL,
	[UserId]					UNIQUEIDENTIFIER		NOT NULL,
	[ProjectId]					UNIQUEIDENTIFIER		NOT NULL,
	[ProjectPlanPhaseId]		UNIQUEIDENTIFIER		NOT NULL,
	[ProductId]					UNIQUEIDENTIFIER		NOT NULL,
	[Quantity]					INT						NOT NULL,
	[InvoiceAmount]				DECIMAL(18,2)			NULL,
	[InvoiceStatusCode]			INT						NOT NULL,
	[InvoicedDate]				DATETIME				NULL,
	[InvoiceRemarks]			NVARCHAR(MAX)			NULL,
	[PurchaseOrderNumber]		NVARCHAR(MAX)			NULL,
	[InvoiceNumber]				NVARCHAR(MAX)			NULL,
	[Date]						DATETIME				NOT NULL,
	[Description]				TEXT					NULL,
	[ProposalId]				UNIQUEIDENTIFIER		NULL,
	[Audit_CreatedBy]			NVARCHAR(MAX)			NOT NULL	DEFAULT (suser_sname()),
	[Audit_CreatedOn]			DATETIME				NOT NULL	DEFAULT GETDATE(),
	[Audit_ModifiedBy]			NVARCHAR(MAX)			NULL,
	[Audit_ModifiedOn]			DATETIME				NULL,
	[Audit_DeletedBy]			NVARCHAR(MAX)			NULL,
	[Audit_DeletedOn]			DATETIME				NULL,
	[Audit_IsDeleted]			BIT						NOT NULL	DEFAULT 0,
	[Audit_VersionId]			UNIQUEIDENTIFIER		NOT NULL	DEFAULT NEWID()
)