CREATE TABLE [dbo].[Project](
	[Id]						UNIQUEIDENTIFIER		NOT NULL,
	[Name]						NVARCHAR(100)			NOT NULL,
	[ProjectTypeId]				UNIQUEIDENTIFIER		NOT NULL,
	[ContactId]					INT						NOT NULL,
	[ProjectManagerId]			UNIQUEIDENTIFIER		NULL,
	[CoProjectManagerId]		UNIQUEIDENTIFIER		NULL,
	[CustomerAssistantId]		UNIQUEIDENTIFIER		NULL,
	[ProposalId]				UNIQUEIDENTIFIER		NULL,
	[PricingModelId]			INT						NOT NULL,
	[StatusCode]				INT						NOT NULL,
	[Remarks]					TEXT					NULL,
	[DepartmentInformation]		TEXT					NULL,
	[Audit_CreatedBy]			NVARCHAR(MAX)			NOT NULL	DEFAULT (suser_sname()),
	[Audit_CreatedOn]			DATETIME				NOT NULL	DEFAULT GETDATE(),
	[Audit_ModifiedBy]			NVARCHAR(MAX)			NULL,
	[Audit_ModifiedOn]			DATETIME				NULL,
	[Audit_DeletedBy]			NVARCHAR(MAX)			NULL,
	[Audit_DeletedOn]			DATETIME				NULL,
	[Audit_IsDeleted]			BIT						NOT NULL	DEFAULT 0,
	[Audit_VersionId]			UNIQUEIDENTIFIER		NOT NULL	DEFAULT NEWID(),
	[LegacyId]					INT						NULL
)