CREATE TABLE [dbo].[ProjectCandidateCategoryDetailType2](
	[Id]							UNIQUEIDENTIFIER		NOT NULL,
	[ProjectCandidateId]			UNIQUEIDENTIFIER		NOT NULL,
	[ProjectCategoryDetailType2Id]	UNIQUEIDENTIFIER		NOT NULL,
	[Deadline]						DATETIME				NULL,
	[InvoiceAmount]					DECIMAL(18,2)			NOT NULL,
	[InvoiceStatusCode]				INT						NOT NULL,
	[InvoicedDate]					DATETIME				NULL,
	[InvoiceRemarks]				NVARCHAR(MAX)			NULL,
	[PurchaseOrderNumber]			NVARCHAR(MAX)			NULL,
	[InvoiceNumber]					NVARCHAR(MAX)			NULL,
	[InvitationSentDate]			DATETIME				NULL,
	[DossierReadyDate]				DATETIME				NULL,
	[InvitationSentDateDone]		BIT						NOT NULL	DEFAULT 0,
	[DossierReadyDateDone]			BIT						NOT NULL	DEFAULT 0,
	[FollowUpDone]					BIT						NOT NULL	DEFAULT 0,
	[Extra1]						NVARCHAR(MAX)			NULL,
	[Extra2]						NVARCHAR(MAX)			NULL,
	[Extra1Done]					BIT						NOT NULL	DEFAULT 0,
	[Extra2Done]					BIT						NOT NULL	DEFAULT 0,
	[ProposalId]					UNIQUEIDENTIFIER		NULL,
	[Audit_CreatedBy]				NVARCHAR(MAX)			NOT NULL	DEFAULT (suser_sname()),
	[Audit_CreatedOn]				DATETIME				NOT NULL	DEFAULT GETDATE(),
	[Audit_ModifiedBy]				NVARCHAR(MAX)			NULL,
	[Audit_ModifiedOn]				DATETIME				NULL,
	[Audit_DeletedBy]				NVARCHAR(MAX)			NULL,
	[Audit_DeletedOn]				DATETIME				NULL,
	[Audit_IsDeleted]				BIT						NOT NULL	DEFAULT 0,
	[Audit_VersionId]				UNIQUEIDENTIFIER		NOT NULL	DEFAULT NEWID()
)