CREATE TABLE [dbo].[Proposal](
	[Id]						UNIQUEIDENTIFIER		NOT NULL,
	[Name]						NVARCHAR(100)			NOT NULL,
	[Description]				TEXT					NULL,
	[ContactId]					INT						NOT NULL,
	[BusinessDeveloperId]		UNIQUEIDENTIFIER		NULL,
	[ExecutorId]				UNIQUEIDENTIFIER		NULL,
	[DateReceived]				DATETIME				NULL,
	[Deadline]					DATETIME				NULL,
	[DateSent]					DATETIME				NULL,
	[DateWon]					DATETIME				NULL,
	[PriceEstimation]			DECIMAL(18,2)			NULL,
	[Prognosis]					DECIMAL(18,2)			NULL,
	[FinalBudget]				DECIMAL(18,2)			NULL,
	[StatusCode]				INT						NOT NULL,
	[StatusReason]				TEXT					NULL,
	[Audit_CreatedBy]			NVARCHAR(MAX)			NOT NULL	DEFAULT (suser_sname()),
	[Audit_CreatedOn]			DATETIME				NOT NULL	DEFAULT GETDATE(),
	[Audit_ModifiedBy]			NVARCHAR(MAX)			NULL,
	[Audit_ModifiedOn]			DATETIME				NULL,
	[Audit_DeletedBy]			NVARCHAR(MAX)			NULL,
	[Audit_DeletedOn]			DATETIME				NULL,
	[Audit_IsDeleted]			BIT						NOT NULL	DEFAULT 0,
	[Audit_VersionId]			UNIQUEIDENTIFIER		NOT NULL	DEFAULT NEWID()
)