CREATE TABLE [dbo].[ReportDefinition](
	[Id]						UNIQUEIDENTIFIER		NOT NULL,
	[ReportTypeId]				INT						NOT NULL,
	[Name]						NVARCHAR(MAX)			NOT NULL,
	[ExportAsXml]				BIT						NULL		DEFAULT 0,
	[ExportAsCsvl]				BIT						NULL		DEFAULT 0,
	[ExportAsImg]				BIT						NULL		DEFAULT 0,
	[ExportAsPdf]				BIT						NULL		DEFAULT 0,
	[ExportAsMhtml]				BIT						NULL		DEFAULT 0,
	[ExportAsHtml4]				BIT						NULL		DEFAULT 0,
	[ExportAsHtml32]			BIT						NULL		DEFAULT 0,
	[ExportAsExcel]				BIT						NULL		DEFAULT 0,
	[ExportAsWord]				BIT						NULL		DEFAULT 0,
	[Location]					NVARCHAR(MAX)			NOT NULL,
	[IsActive]					BIT						NOT NULL	DEFAULT 1,
	[Audit_CreatedBy]			NVARCHAR(MAX)			NOT NULL	DEFAULT (suser_sname()),
	[Audit_CreatedOn]			DATETIME				NOT NULL	DEFAULT GETDATE(),
	[Audit_ModifiedBy]			NVARCHAR(MAX)			NULL,
	[Audit_ModifiedOn]			DATETIME				NULL,
	[Audit_DeletedBy]			NVARCHAR(MAX)			NULL,
	[Audit_DeletedOn]			DATETIME				NULL,
	[Audit_IsDeleted]			BIT						NOT NULL	DEFAULT 0,
	[Audit_VersionId]			UNIQUEIDENTIFIER		NOT NULL	DEFAULT NEWID()
)